name: Build and Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          make

      - name: Run test
        id: test
        continue-on-error: true
        run: |
          build/tests/test
          echo "::set-output name=result::$?banana"

      - name: Check test result
        run: |
          result="${{ steps.test.outputs.result }}"
          if [ "$result" != 1 ]; then
            exit 1
          fi